### ISSUE TITLE
ember-qunit-codemod for addon errors out with non-js files

### ISSUE THREAD

**Issue by rajasegar-c** [ember-cli/ember-cli-update-codemods-manifest#126]
```
ERR: tests/dummy/public/robots.txt Transformation error (Unexpected token (1:0))
SyntaxError: Unexpected token (1:0)
```
I think we need to add the glob pattern to the path here 
https://github.com/ember-cli/ember-cli-update-codemods-manifest/blob/867fa77e2d4bd66cbc547e8ba2cd866a3aab709c/packages/addon/manifest.json#L14
```
    "commands": ["ember-qunit-codemod convert-module-for-to-setup-test ./tests/**/*.js"]
```

Will be glad to submit a PR

**Comment by kellyselden** [comment]
sounds good to me
