### ISSUE TITLE
ember angle-brackets-codemod wrong target

### ISSUE THREAD

**Issue by rajasegar** [ember-cli/ember-cli-update-codemods-manifest#143]
The angle-brackets codemod for addons targets the folder `app/templates`. 
Shouldn't it be pointing to the `addon/templates` folder instead?
https://github.com/ember-cli/ember-cli-update-codemods-manifest/blob/db56d248fdb23a43226cad7fede7113e5c511dff/packages/addon/manifest.json#L87

Also if Telemetry is made optional we can use the latest version of the codemod instead of using the older 2.x version
Related issue here:
https://github.com/ember-codemods/ember-angle-brackets-codemod/issues/282

**Comment by kellyselden** [comment]
Yeah we should fix that.
