### ISSUE TITLE
ember-data-codemod runs against all of node_modules

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-cli-update-codemods-manifest#59]
It appears that the ember-data-codemod is running on every file in my project, including all of node_modules.

I think the extra `.` on this line may be the cause:

https://github.com/ember-cli/ember-cli-update-codemods-manifest/blob/dfac3edee8cb6f4a1678046934b6889d19ddd512/manifest.json#L131

**Comment by kellyselden** [comment]
According to the docs, that dot means run all codemods in that lib, rather than individually by name. @runspired care to correct me?

**Comment by ef4** [comment]
Oh ok, I was just guessing about the dot as the cause. Could be something else that's responsible. 

The symptom is real though. The codemod rewrote everything in node_modules, including ember-data itself, which left things in a weirdly broken state.

If other people aren't seeing the problem I can try to make a shareable reproduction.

**Comment by kellyselden** [comment]
Closing as I think this is a problem with the codemod, not how we use it.

**Comment by kellyselden** [comment]
Feel free to tell me otherwise.

**Comment by runspired** [comment]
I’d like to see a reproduction. Haven’t observed this myself. Cc @dcyriller for awareness

**Comment by ef4** [comment]
I left repro instructions in https://github.com/ember-codemods/ember-data-codemod/issues/54

**Comment by laura-bergoens** [comment]
I'm encountering the same issue here. I've updated ember-cli-udpate, ran all codemods.
I noticed it took ~ 650 seconds to process. I re-ran it and payed more attention to it. The terminal indicated that the codemods will apply on 42000 files approx. It's the ember-data codemod.

**Comment by dcyriller** [comment]
oups, README's instructions are a bit ahead of the current released version.

https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/71 should fix the issue while we prepare a new version.
