### ISSUE TITLE
update ember-qunit-codemod to the new syntax

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-update-codemods-manifest#6]
cc @rwjblue

**Comment by rajasegar** [comment]
Can we have a detailed explanation of the issue, I didn't get the new syntax part?

**Comment by kellyselden** [comment]
@NullVoxPopuli Actually did this in https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/14, so it's good now.
