### ISSUE TITLE
update es5-getter-ember-codemod to the new syntax

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli-update-codemods-manifest#9]

**Comment by rajasegar** [comment]
@kellyselden New syntax? Can you please elaborate....

**Comment by kellyselden** [comment]
The manifest has the old style `jscodeshift -t https://rawgit.com/rondale-sc/es5-getter-ember-codemod/a2f9fc1c14ba30afc48cb7106ad259eb78dee9b7/es5-getter-ember-codemod.js ./app`, but the codemod was updated to a new style mentioned in its [README](https://github.com/ember-codemods/es5-getter-ember-codemod): `github:rondale-sc/es5-getter-ember-codemod es5-getter-ember-codemod app/**/*.js`.
